name: SonarQube Workflow
on:
  pull_request:
    branches:
      - develop
      - qa
      - staging
      - master
jobs:
  build:
    name: SONARQUBE
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/Nickelfox/sonarqube-js-workflow/blob/main/.github/workflows/sonarqube-workflow.yml@main
